// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calc_current_exposure_cpp
double calc_current_exposure_cpp(double exposure, double start_time, double final_day, double clr);
RcppExport SEXP multdr_calc_current_exposure_cpp(SEXP exposureSEXP, SEXP start_timeSEXP, SEXP final_daySEXP, SEXP clrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< double >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< double >::type final_day(final_daySEXP);
    Rcpp::traits::input_parameter< double >::type clr(clrSEXP);
    __result = Rcpp::wrap(calc_current_exposure_cpp(exposure, start_time, final_day, clr));
    return __result;
END_RCPP
}
// calc_risk_mult_cpp
double calc_risk_mult_cpp(double exposure, double start_time, double final_day, double hazard_risk, double clr);
RcppExport SEXP multdr_calc_risk_mult_cpp(SEXP exposureSEXP, SEXP start_timeSEXP, SEXP final_daySEXP, SEXP hazard_riskSEXP, SEXP clrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type exposure(exposureSEXP);
    Rcpp::traits::input_parameter< double >::type start_time(start_timeSEXP);
    Rcpp::traits::input_parameter< double >::type final_day(final_daySEXP);
    Rcpp::traits::input_parameter< double >::type hazard_risk(hazard_riskSEXP);
    Rcpp::traits::input_parameter< double >::type clr(clrSEXP);
    __result = Rcpp::wrap(calc_risk_mult_cpp(exposure, start_time, final_day, hazard_risk, clr));
    return __result;
END_RCPP
}
// simulate_infection_times_cpp
double simulate_infection_times_cpp(NumericVector exposure_set, NumericVector time_set, double lag, double hazard_risk, double clr);
RcppExport SEXP multdr_simulate_infection_times_cpp(SEXP exposure_setSEXP, SEXP time_setSEXP, SEXP lagSEXP, SEXP hazard_riskSEXP, SEXP clrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type exposure_set(exposure_setSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type time_set(time_setSEXP);
    Rcpp::traits::input_parameter< double >::type lag(lagSEXP);
    Rcpp::traits::input_parameter< double >::type hazard_risk(hazard_riskSEXP);
    Rcpp::traits::input_parameter< double >::type clr(clrSEXP);
    __result = Rcpp::wrap(simulate_infection_times_cpp(exposure_set, time_set, lag, hazard_risk, clr));
    return __result;
END_RCPP
}
