# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'  This is a C++ version of the current remaining exposure function
calc_current_exposure_cpp <- function(exposure, start_time, final_day, clr) {
    .Call('multdr_calc_current_exposure_cpp', PACKAGE = 'multdr', exposure, start_time, final_day, clr)
}

#'  This is a C++ version of the risk calculation function
calc_risk_mult_cpp <- function(exposure, start_time, final_day, hazard_risk, clr) {
    .Call('multdr_calc_risk_mult_cpp', PACKAGE = 'multdr', exposure, start_time, final_day, hazard_risk, clr)
}

#'  This is a C++ version of the simulation function, that will replace the while loop in the simulation call
#'  Assigning infection time to sample time is done later
#'  @export
simulate_infection_times_cpp <- function(exposure_set, time_set, hazard_risk, clr) {
    .Call('multdr_simulate_infection_times_cpp', PACKAGE = 'multdr', exposure_set, time_set, hazard_risk, clr)
}

